import Foundation

public enum SampleRecipes {
    public static let panSearedChicken = Recipe(
        id: "pan-seared-chicken", title: "Pan-Seared Chicken",
        subtitle: "Two sides, one pan · about 20 min · serves 2",
        ingredients: ["2 boneless chicken breasts of similar thickness", "1 tablespoon cooking oil",
                      "½ teaspoon salt", "¼ teaspoon black pepper", "Food thermometer"],
        steps: [
            RecipeStep(id: "chicken-season", title: "Season chicken",
                       fullInstruction: "Pat 2 chicken breasts dry. Season both sides with ½ teaspoon salt and ¼ teaspoon pepper. Wash hands and clean surfaces after handling raw chicken.",
                       glassesInstruction: "½ tsp salt + ¼ tsp pepper.\nWash hands after."),
            RecipeStep(id: "chicken-heat", title: "Heat the pan",
                       fullInstruction: "Add 1 tablespoon cooking oil to a skillet over medium heat. Heat until the oil shimmers. Keep the pan attended.",
                       glassesInstruction: "1 tbsp oil.\nHeat over medium.",
                       prerequisiteStepIDs: ["chicken-season"], requiresContinuousAttention: true),
            RecipeStep(id: "chicken-add", title: "Add chicken to the pan",
                       fullInstruction: "Carefully place the seasoned chicken in the pan, laying it away from you. Cooking Watch can detect placement and start the first-side timer.",
                       glassesInstruction: "Place chicken\nin the pan.", expectedEvents: [.chickenAddedToPan],
                       prerequisiteStepIDs: ["chicken-heat"], requiresContinuousAttention: true,
                       allowsAutomaticProgression: true),
            RecipeStep(id: "chicken-first-side", title: "Cook the first side",
                       fullInstruction: "Cook the first side for about 5 minutes. Adjust heat if it smokes. Flip when ready; the timer is a reminder, not a food-safety check.",
                       glassesInstruction: "Cook first side.\nCheck at 5 min.", expectedEvents: [.chickenFlipped],
                       optionalTimer: TimerSpecification(label: "Chicken first side", duration: 300),
                       prerequisiteStepIDs: ["chicken-add"], requiresContinuousAttention: true,
                       allowsAutomaticProgression: true),
            RecipeStep(id: "chicken-flip", title: "Flip the chicken",
                       fullInstruction: "Flip the chicken with clean tongs. Cooking Watch can detect the flip and start the second-side timer, even if the first-side timer is still running.",
                       glassesInstruction: "Flip chicken\nwith clean tongs.", expectedEvents: [.chickenFlipped],
                       prerequisiteStepIDs: ["chicken-first-side"], requiresContinuousAttention: true,
                       allowsAutomaticProgression: true),
            RecipeStep(id: "chicken-second-side", title: "Cook the second side",
                       fullInstruction: "Cook the second side for about 4 minutes. Check the thickest part with a food thermometer: poultry must reach 165°F / 74°C. Continue cooking and recheck if below that temperature. Time and appearance cannot establish safety.",
                       glassesInstruction: "Cook second side.\nThermometer: 165°F / 74°C.",
                       expectedEvents: [.chickenRemovedFromPan],
                       optionalTimer: TimerSpecification(label: "Chicken second side", duration: 240),
                       prerequisiteStepIDs: ["chicken-flip"], requiresContinuousAttention: true,
                       allowsAutomaticProgression: true),
            RecipeStep(id: "chicken-remove", title: "Remove the chicken",
                       fullInstruction: "Use a food thermometer to verify at least 165°F / 74°C in the thickest part before removing the chicken to a clean plate. Vision cannot verify its internal temperature. If below temperature, keep cooking.",
                       glassesInstruction: "Verify 165°F / 74°C.\nMove to clean plate.", expectedEvents: [.chickenRemovedFromPan],
                       prerequisiteStepIDs: ["chicken-second-side"], requiresContinuousAttention: true,
                       allowsAutomaticProgression: true),
            RecipeStep(id: "chicken-rest", title: "Rest the chicken",
                       fullInstruction: "Rest on a clean plate for 3 minutes before slicing. Only serve after a food thermometer has verified 165°F / 74°C; this timer and camera observations do not verify safety.",
                       glassesInstruction: "Rest 3 min.\nServe only after 165°F / 74°C.",
                       optionalTimer: TimerSpecification(label: "Chicken rest", duration: 180),
                       prerequisiteStepIDs: ["chicken-remove"])
        ])

    public static let simplePasta = Recipe(
        id: "simple-pasta", title: "Simple Pasta",
        subtitle: "A dependable stovetop staple · about 20 min · serves 2",
        ingredients: ["200 g dried pasta", "2 L water", "2 teaspoons salt", "1 tablespoon olive oil"],
        steps: [
            RecipeStep(id: "pasta-fill", title: "Fill the pot",
                       fullInstruction: "Add 2 liters of water to a large pot. Leave enough space to prevent boiling over.",
                       glassesInstruction: "Fill pot with\n2 L water."),
            RecipeStep(id: "pasta-pot", title: "Place pot on stove",
                       fullInstruction: "Place the pot securely on a burner. Turn the handle inward and heat the water.",
                       glassesInstruction: "Pot onto stove.\nHandle inward.", expectedEvents: [.potPlacedOnStove],
                       prerequisiteStepIDs: ["pasta-fill"], allowsAutomaticProgression: true),
            RecipeStep(id: "pasta-boil", title: "Bring water to a boil",
                       fullInstruction: "Wait for a rolling boil, then add 2 teaspoons salt. Mark this step done when the water is boiling; Cooking Watch does not verify boiling.",
                       glassesInstruction: "Rolling boil.\nAdd 2 tsp salt.",
                       prerequisiteStepIDs: ["pasta-pot"], requiresContinuousAttention: true),
            RecipeStep(id: "pasta-add", title: "Add the pasta",
                       fullInstruction: "Add 200 g dried pasta to the boiling water and stir. Cooking Watch can start a 10-minute reminder; follow the cooking time on your pasta package.",
                       glassesInstruction: "Add 200 g pasta.\nStir gently.", expectedEvents: [.pastaAddedToWater],
                       prerequisiteStepIDs: ["pasta-boil"], requiresContinuousAttention: true,
                       allowsAutomaticProgression: true),
            RecipeStep(id: "pasta-cook", title: "Cook and check the pasta",
                       fullInstruction: "Stir occasionally and keep the pot from boiling over. Start checking texture at the package's recommended time. The 10-minute timer is a reminder; extend it if needed.",
                       glassesInstruction: "Stir occasionally.\nCheck package time.",
                       optionalTimer: TimerSpecification(label: "Pasta", duration: 600),
                       prerequisiteStepIDs: ["pasta-add"], requiresContinuousAttention: true),
            RecipeStep(id: "pasta-drain", title: "Drain and finish",
                       fullInstruction: "When the pasta has the texture you want, turn off the heat. Drain carefully away from steam, then toss with 1 tablespoon olive oil.",
                       glassesInstruction: "Heat off. Drain.\nToss with 1 tbsp oil.",
                       prerequisiteStepIDs: ["pasta-cook"], requiresContinuousAttention: true)
        ])

    public static let sauteedVegetables = Recipe(
        id: "sauteed-vegetables", title: "Sautéed Vegetables",
        subtitle: "A quick colorful side · about 15 min · serves 2",
        ingredients: ["2 cups chopped vegetables", "1 tablespoon cooking oil", "¼ teaspoon salt"],
        steps: [
            RecipeStep(id: "veg-prep", title: "Prepare the vegetables",
                       fullInstruction: "Wash and cut 2 cups of vegetables into similarly sized pieces so they cook evenly.",
                       glassesInstruction: "Wash and chop\n2 cups vegetables."),
            RecipeStep(id: "veg-heat", title: "Heat the skillet",
                       fullInstruction: "Heat 1 tablespoon cooking oil in a skillet over medium heat. Keep the pan attended.",
                       glassesInstruction: "1 tbsp oil.\nMedium heat.",
                       prerequisiteStepIDs: ["veg-prep"], requiresContinuousAttention: true),
            RecipeStep(id: "veg-add", title: "Add the vegetables",
                       fullInstruction: "Add the prepared vegetables to the skillet, carefully avoiding splashes, and sprinkle with ¼ teaspoon salt.",
                       glassesInstruction: "Add vegetables.\n¼ tsp salt.", expectedEvents: [.ingredientAdded],
                       prerequisiteStepIDs: ["veg-heat"], requiresContinuousAttention: true,
                       allowsAutomaticProgression: true),
            RecipeStep(id: "veg-cook", title: "Cook and stir",
                       fullInstruction: "Cook for about 5 minutes, stirring often, until the texture suits you. Adjust heat as needed. The timer is a reminder to check the food.",
                       glassesInstruction: "Stir often.\nCheck at 5 min.",
                       optionalTimer: TimerSpecification(label: "Vegetables", duration: 300),
                       prerequisiteStepIDs: ["veg-add"], requiresContinuousAttention: true),
            RecipeStep(id: "veg-serve", title: "Finish and serve",
                       fullInstruction: "Check texture, turn off the heat, and transfer the vegetables to a serving dish.",
                       glassesInstruction: "Check texture.\nHeat off and serve.",
                       prerequisiteStepIDs: ["veg-cook"])
        ])

    public static let all: [Recipe] = [panSearedChicken, simplePasta, sauteedVegetables]
}
